function accel = compute_accel(I1,I2,Q1,Q2,Q1dot,Q2dot,T1,T2,g,l1,m1,m2,r1,r2)
%COMPUTE_ACCEL
%    ACCEL = COMPUTE_ACCEL(I1,I2,Q1,Q2,Q1DOT,Q2DOT,T1,T2,G,L1,M1,M2,R1,R2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    26-Jan-2016 09:28:45

t2 = l1.^2;
t3 = r2.^2;
t4 = r1.^2;
t5 = m2.^2;
t6 = cos(Q2);
t7 = cos(Q1);
t8 = sin(Q2);
t9 = Q1dot.^2;
t10 = Q2dot.^2;
t11 = I1.*I2;
t12 = t2.*t3.*t5;
t13 = I2.*m2.*t2;
t14 = I2.*m1.*t4;
t15 = I1.*m2.*t3;
t16 = m1.*m2.*t3.*t4;
t17 = t6.^2;
t18 = t11+t12+t13+t14+t15+t16-t2.*t3.*t5.*t17;
t19 = 1.0./t18;
t20 = I2.*T1;
t21 = T1.*m2.*t3;
t22 = Q1+Q2;
t23 = cos(t22);
t24 = l1.*r2.*t3.*t5.*t8.*t9;
t25 = l1.*r2.*t3.*t5.*t8.*t10;
t26 = I2.*l1.*m2.*r2.*t8.*t9;
t27 = I2.*l1.*m2.*r2.*t8.*t10;
t28 = Q1dot.*Q2dot.*l1.*r2.*t3.*t5.*t8.*2.0;
t29 = g.*l1.*t3.*t5.*t6.*t23;
t30 = I2.*Q1dot.*Q2dot.*l1.*m2.*r2.*t8.*2.0;
accel = [t19.*(t20+t21+t24+t25+t26+t27+t28+t29+t30-I2.*T2-T2.*m2.*t3-I2.*g.*l1.*m2.*t7-I2.*g.*m1.*r1.*t7-T2.*l1.*m2.*r2.*t6-g.*l1.*t3.*t5.*t7+t2.*t3.*t5.*t6.*t8.*t9-g.*m1.*m2.*r1.*t3.*t7),-t19.*(t20+t21+t24+t25+t26+t27+t28+t29+t30-I1.*T2-I2.*T2-T2.*m2.*t2-T2.*m1.*t4-T2.*m2.*t3-I2.*g.*l1.*m2.*t7-I2.*g.*m1.*r1.*t7+I1.*g.*m2.*r2.*t23+T1.*l1.*m2.*r2.*t6-T2.*l1.*m2.*r2.*t6.*2.0-g.*l1.*t3.*t5.*t7+g.*r2.*t2.*t5.*t23-g.*r2.*t2.*t5.*t6.*t7+l1.*r2.*t2.*t5.*t8.*t9+t2.*t3.*t5.*t6.*t8.*t9.*2.0+t2.*t3.*t5.*t6.*t8.*t10+I1.*l1.*m2.*r2.*t8.*t9-g.*m1.*m2.*r1.*t3.*t7+g.*m1.*m2.*r2.*t4.*t23+Q1dot.*Q2dot.*t2.*t3.*t5.*t6.*t8.*2.0+l1.*m1.*m2.*r2.*t4.*t8.*t9-g.*l1.*m1.*m2.*r1.*r2.*t6.*t7)];
